# Generated by Django 4.1.7 on 2023-03-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userprofile',
            new_name='user',
        ),
    ]
